export const FLAG_REGIONS = [
  "AC", "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX",
  "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR",
  "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM",
  "CN", "CO", "CP", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DG", "DJ", "DK", "DM", "DO",
  "DZ", "EA", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "EU", "FI", "FJ", "FK", "FM", "FO", "FR",
  "GA", "GB", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT",
  "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU", "IC", "ID", "IE", "IM", "IN", "IO", "IQ",
  "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW",
  "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD",
  "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV",
  "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ",
  "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA",
  "RE", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL",
  "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ", "TA", "TC", "TD", "TF", "TG", "TH",
  "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "UN", "US",
  "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "XK", "YE", "YT", "ZA", "ZM",
  "ZW"
];

export const FLAG_SUBDIVISIONS = ["\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}"];

export const FLAG_SPECIALS = ["\u{1F3C1}", "\u{1F6A9}", "\u{1F3F3}\uFE0F", "\u{1F3F4}",
  "\u{1F3F3}\uFE0F\u200D\u{1F308}", "\u{1F3F3}\uFE0F\u200D\u26A7\uFE0F",
  "\u{1F3F4}\u200D\u2620\uFE0F"];

export const FLAG_EXTRA_NAMES: Record<string, string> = {
  [FLAG_SPECIALS[0]]: "flag chequered checkered race finish",
  [FLAG_SPECIALS[1]]: "flag triangular red post golf",
  [FLAG_SPECIALS[2]]: "flag white surrender",
  [FLAG_SPECIALS[3]]: "flag black",
  [FLAG_SPECIALS[4]]: "flag rainbow pride lgbt gay",
  [FLAG_SPECIALS[5]]: "flag transgender trans pride",
  [FLAG_SPECIALS[6]]: "flag pirate jolly roger skull",
  [FLAG_SUBDIVISIONS[0]]: "flag england english gbeng united kingdom",
  [FLAG_SUBDIVISIONS[1]]: "flag scotland scottish gbsct united kingdom",
  [FLAG_SUBDIVISIONS[2]]: "flag wales welsh gbwls united kingdom"
};

export function regionFlag(code: string) {
  return String.fromCodePoint(...[...code].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    emojis: [
      "😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃",
      "😉", "😊", "😇", "🥰", "😍", "🤩", "😘", "😗", "😚", "😙",
      "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗", "🤭", "🤫", "🤔",
      "🤐", "🤨", "😐", "😑", "😶", "😏", "😒", "🙄", "😬", "🤥",
      "😌", "😔", "😪", "🤤", "😴", "😷", "🤒", "🤕", "🤢", "🤮",
      "🤧", "🥵", "🥶", "🥴", "😵", "🤯", "🤠", "🥳", "😎", "🤓",
      "🧐", "😕", "😟", "🙁", "😮", "😯", "😲", "😳", "🥺", "😦",
      "😧", "😨", "😰", "😥", "😢", "😭", "😱", "😖", "😣", "😞",
      "😓", "😩", "😫", "🥱", "😤", "😡", "😠", "🤬", "😈", "👿",
      "💀", "☠️", "💩", "🤡", "👹", "👺", "👻", "👽", "👾", "🤖",
      "👶", "👧", "🧒", "👦", "👩", "🧑", "👨", "👵", "🧓", "👴",
      "👮", "🕵️", "💂", "👷", "🤴", "👸", "🧙", "🧚", "🧛", "🧜",
      "💃", "🕺", "👫", "👬", "👭", "💏", "💑", "👪"
    ]
  },
  {
    id: "gestures",
    emojis: [
      "👋", "🤚", "🖐️", "✋", "🖖", "👌", "🤌", "🤏", "✌️", "🤞",
      "🤟", "🤘", "🤙", "👈", "👉", "👆", "🖕", "👇", "☝️", "👍",
      "👎", "✊", "👊", "🤛", "🤜", "👏", "🙌", "👐", "🤲", "🤝",
      "🙏", "✍️", "💅", "🤳", "💪", "🦾", "🦿", "🦵", "🦶", "👂",
      "🦻", "👃", "🧠", "🫀", "🫁", "🦷", "🦴", "👀", "👁️", "👅", "👄"
    ]
  },
  {
    id: "animals",
    emojis: [
      "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯",
      "🦁", "🐮", "🐷", "🐽", "🐸", "🐵", "🙈", "🙉", "🙊", "🐒",
      "🐔", "🐧", "🐦", "🐤", "🦆", "🦅", "🦉", "🦇", "🐺", "🐗",
      "🐴", "🦄", "🐝", "🐛", "🦋", "🐌", "🐞", "🐜", "🕷️", "🦂",
      "🐢", "🐍", "🦎", "🦖", "🦕", "🐙", "🦑", "🦐", "🦀", "🐡",
      "🐠", "🐟", "🐬", "🐳", "🐋", "🦈", "🌵", "🎄", "🌲", "🌳",
      "🌴", "🌱", "🌿", "🍀", "🍁", "🍂", "🌹", "🌻", "🌼", "🌸", "💐", "🍄"
    ]
  },
  {
    id: "food",
    emojis: [
      "🍏", "🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐",
      "🍒", "🍑", "🥭", "🍍", "🥥", "🥝", "🍅", "🍆", "🥑", "🥦",
      "🥬", "🥒", "🌶️", "🌽", "🥕", "🧄", "🧅", "🥔", "🍠", "🥐",
      "🥯", "🍞", "🥖", "🥨", "🧀", "🥚", "🍳", "🧈", "🥞", "🧇",
      "🥓", "🥩", "🍗", "🍖", "🌭", "🍔", "🍟", "🍕", "🥪", "🥙",
      "🌮", "🌯", "🥗", "🥘", "🍝", "🍜", "🍲", "🍛", "🍣", "🍱",
      "🥟", "🍤", "🍙", "🍚", "🍘", "🍥", "🍡", "🍧", "🍨", "🍦",
      "🥧", "🍰", "🎂", "🍮", "🍭", "🍬", "🍫", "🍿", "🍩", "🍪",
      "☕", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂",
      "🥃", "🥤", "🧋", "🧃", "🧉", "🧊"
    ]
  },
  {
    id: "activities",
    emojis: [
      "⚽", "🏀", "🏈", "⚾", "🎾", "🏐", "🏉", "🎱", "🏓", "🏸",
      "🏒", "🏑", "🏏", "🥅", "⛳", "🏹", "🎣", "🥊", "🥋", "🎽",
      "🛹", "🛼", "🛷", "⛸️", "🎿", "⛷️", "🏂", "🏋️", "🤸", "⛹️",
      "🏇", "🏄", "🏊", "🤽", "🚣", "🧗", "🚵", "🚴", "🏆", "🥇",
      "🥈", "🥉", "🏅", "🎖️", "🎗️", "🎫", "🎟️", "🎪", "🤹", "🎭",
      "🎨", "🎬", "🎤", "🎧", "🎼", "🎹", "🥁", "🎷", "🎺", "🎸",
      "🎻", "🎲", "♟️", "🎯", "🎳", "🎮", "🎰", "🧩",
      "🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐",
      "🛻", "🚚", "🚛", "🚜", "🛵", "🏍️", "🚲", "🛴", "🛹", "🚡",
      "🚠", "🚟", "🚃", "🚋", "🚞", "🚝", "🚄", "🚅", "🚈", "🚂",
      "🚆", "🚇", "🚊", "🚉", "✈️", "🛫", "🛬", "🛩️", "💺", "🛰️",
      "🚀", "🛸", "🚁", "🛶", "⛵", "🚤", "🛥️", "🛳️", "⛴️", "🚢",
      "⚓", "🗺️", "🌍", "🌎", "🌏", "🗻", "🏕️", "🏖️", "🏜️", "🏝️",
      "🏟️", "🏛️", "🏗️", "🏘️", "🏙️", "🏠", "🏡", "🏢", "🏥", "🏦",
      "🏨", "🏫", "🏬", "🏭", "🏯", "🏰", "💒", "🗼", "🗽", "⛪", "🕌", "⛩️"
    ]
  },
  {
    id: "objects",
    emojis: [
      "⌚", "📱", "💻", "⌨️", "🖥️", "🖨️", "🖱️", "🖲️", "🕹️", "💽",
      "💾", "💿", "📀", "📼", "📷", "📸", "📹", "🎥", "📽️", "📞",
      "☎️", "📟", "📠", "📺", "📻", "🎙️", "🎚️", "🎛️", "🧭", "⏱️",
      "⏲️", "⏰", "⌛", "⏳", "📡", "🔋", "🔌", "💡", "🔦", "🕯️",
      "💸", "💵", "💴", "💶", "💷", "🪙", "💰", "💳", "💎", "⚖️",
      "🧰", "🧲", "🔧", "🔨", "⚒️", "🛠️", "⛏️", "🔩", "⚙️", "🧱",
      "⛓️", "🔫", "🧨", "💣", "🏹", "🛡️", "🗡️", "⚔️", "🔪", "🪓",
      "🔒", "🔓", "🔐", "🔑", "🗝️", "⚰️", "⚱️", "🧿", "💄", "💍",
      "👑", "🎩", "🧢", "👒", "🎓", "⛑️", "🪖", "💼", "🎒", "👝", "👛", "👜",
      "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔",
      "❣️", "💕", "💞", "💓", "💗", "💖", "💘", "💝", "💟", "💯",
      "💢", "🔥", "✨", "⭐", "🎉", "🎊", "☕", "❗", "❓", "✅",
      "❌", "⭕", "🛑", "⛔", "🚫", "⚠️", "♻️", "➕", "➖", "➗", "✖️"
    ]
  },
  {
    id: "flags",
    emojis: [...FLAG_SPECIALS, ...FLAG_SUBDIVISIONS, ...FLAG_REGIONS.map(regionFlag)]
  }
];

export const EMOJI_NAMES: Record<string, string> = {
  // Smileys & People
  "😀": "smile grinning face happy",
  "😃": "smile grinning happy face",
  "😄": "smile happy open mouth",
  "😁": "grin smile happy",
  "😆": "laugh smiling",
  "😅": "sweat smile nervous laugh",
  "🤣": "rofl laugh rolling",
  "😂": "joy laugh tears crying happy",
  "🙂": "smile",
  "🙃": "upside face",
  "😉": "wink",
  "😊": "smile blush happy",
  "😇": "angel innocent",
  "🥰": "love hearts smiling",
  "😍": "love heart eyes",
  "🤩": "star eyes wow",
  "😘": "kiss",
  "😗": "kiss",
  "😚": "kiss",
  "😙": "kiss",
  "😋": "yum tasty",
  "😛": "tongue",
  "😜": "wink tongue",
  "🤪": "crazy zany",
  "😝": "tongue playful",
  "🤑": "money rich",
  "🤗": "hug",
  "🤭": "giggle oops",
  "🤫": "shh quiet",
  "🤔": "think hmm",
  "🤐": "zip mouth",
  "🤨": "skeptical raised eyebrow",
  "😐": "neutral",
  "😑": "expressionless",
  "😶": "silent no mouth",
  "😏": "smirk",
  "😒": "unamused",
  "🙄": "roll eyes",
  "😬": "grimace",
  "🤥": "lie liar",
  "😌": "relieved",
  "😔": "sad pensive",
  "😪": "sleepy tired",
  "🤤": "drool",
  "😴": "sleep sleeping",
  "😷": "mask sick",
  "🤒": "sick ill",
  "🤕": "hurt injured",
  "🤢": "nauseated sick",
  "🤮": "vomit puke",
  "🤧": "sneeze",
  "🥵": "hot overheated",
  "🥶": "cold freezing",
  "🥴": "woozy drunk",
  "😵": "dizzy dead",
  "🤯": "explode mind blown",
  "🤠": "cowboy",
  "🥳": "party celebrate birthday",
  "😎": "cool sunglasses",
  "🤓": "nerd",
  "🧐": "monocle",
  "😕": "confused",
  "😟": "worried",
  "🙁": "frown sad",
  "😮": "surprised wow",
  "😯": "surprised",
  "😲": "astonished",
  "😳": "flushed blush",
  "🥺": "pleading puppy",
  "😦": "frown",
  "😧": "anguished",
  "😨": "fearful scared",
  "😰": "anxious sweat",
  "😥": "sad disappointed",
  "😢": "cry tear sad",
  "😭": "cry sob tears bawl",
  "😱": "scream scared",
  "😖": "confounded",
  "😣": "persevere",
  "😞": "disappointed sad",
  "😓": "sweat downcast",
  "😩": "weary tired",
  "😫": "tired exhausted",
  "🥱": "yawning bored",
  "😤": "frustrated triumph",
  "😡": "angry rage pout",
  "😠": "angry mad",
  "🤬": "cursing swear",
  "😈": "devil evil smile",
  "👿": "devil angry",
  "💀": "skull dead skeleton",
  "☠️": "skull crossbones danger",
  "💩": "poop poop shit",
  "🤡": "clown",
  "👹": "ogre monster",
  "👺": "goblin",
  "👻": "ghost halloween",
  "👽": "alien",
  "👾": "alien monster",
  "🤖": "robot",
  // Gestures
  "👋": "wave hi hello bye",
  "🤚": "raised hand back",
  "🖐️": "hand fingers",
  "✋": "hand stop",
  "🖖": "vulcan star trek",
  "👌": "ok perfect",
  "🤌": "pinched fingers italian",
  "🤏": "pinch small",
  "✌️": "peace victory",
  "🤞": "crossed fingers luck",
  "🤟": "love you hand",
  "🤘": "rock devil horns",
  "🤙": "call me",
  "👈": "point left",
  "👉": "point right",
  "👆": "point up",
  "🖕": "middle finger",
  "👇": "point down",
  "☝️": "point up",
  "👍": "thumbs up good yes",
  "👎": "thumbs down no",
  "✊": "fist",
  "👊": "punch fist",
  "👏": "clap applause",
  "🙌": "raised hands celebrate",
  "👐": "open hands",
  "🤲": "palms up",
  "🤝": "handshake deal",
  "🙏": "pray please thanks",
  "💪": "muscle strong power",
  "👀": "eyes look",
  "👁️": "eye",
  "👅": "tongue",
  "👄": "lips mouth",
  // Animals
  "🐶": "dog puppy",
  "🐱": "cat kitten",
  "🐭": "mouse",
  "🐹": "hamster",
  "🐰": "rabbit bunny",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda",
  "🐨": "koala",
  "🐯": "tiger",
  "🦁": "lion",
  "🐮": "cow",
  "🐷": "pig",
  "🐸": "frog",
  "🐵": "monkey",
  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🦆": "duck",
  "🦅": "eagle",
  "🦉": "owl",
  "🦇": "bat",
  "🐺": "wolf",
  "🐴": "horse",
  "🦄": "unicorn",
  "🐝": "bee",
  "🐛": "bug caterpillar",
  "🦋": "butterfly",
  "🐌": "snail",
  "🐞": "ladybug",
  "🐜": "ant",
  "🕷️": "spider",
  "🦂": "scorpion",
  "🐢": "turtle",
  "🐍": "snake",
  "🦖": "dinosaur t-rex",
  "🦕": "dinosaur",
  "🐙": "octopus",
  "🦑": "squid",
  "🦀": "crab",
  "🐟": "fish",
  "🐬": "dolphin",
  "🐳": "whale",
  "🐋": "whale",
  "🦈": "shark",
  "🌵": "cactus",
  "🎄": "christmas tree",
  "🌲": "tree",
  "🌴": "palm tree",
  "🌹": "rose flower",
  "🌻": "sunflower",
  "🌸": "cherry blossom flower",
  "🍀": "clover luck",
  "🍁": "maple leaf",
  "🍄": "mushroom",
  // Food
  "🍏": "apple",
  "🍎": "apple red",
  "🍊": "orange",
  "🍋": "lemon",
  "🍌": "banana",
  "🍉": "watermelon",
  "🍇": "grapes",
  "🍓": "strawberry",
  "🍒": "cherry",
  "🍑": "peach",
  "🍍": "pineapple",
  "🥥": "coconut",
  "🍅": "tomato",
  "🍆": "eggplant",
  "🥑": "avocado",
  "🥕": "carrot",
  "🌽": "corn",
  "🍞": "bread",
  "🥖": "baguette",
  "🧀": "cheese",
  "🥚": "egg",
  "🍳": "cooking fry egg",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🥓": "bacon",
  "🥩": "steak meat",
  "🍗": "chicken leg",
  "🍔": "burger hamburger",
  "🍟": "fries",
  "🍕": "pizza",
  "🥪": "sandwich",
  "🥗": "salad",
  "🍝": "pasta spaghetti",
  "🍜": "noodles ramen",
  "🍣": "sushi",
  "🍙": "rice ball",
  "🍚": "rice",
  "🍦": "ice cream",
  "🍰": "cake",
  "🎂": "birthday cake",
  "🍩": "donut",
  "🍪": "cookie",
  "🍫": "chocolate",
  "🍿": "popcorn",
  "☕": "coffee",
  "🍵": "tea",
  "🍷": "wine",
  "🍺": "beer",
  "🍻": "beers cheers",
  "🥂": "champagne toast",
  "🥤": "soda drink",
  // Activities & Travel
  "⚽": "soccer football ball",
  "🏀": "basketball",
  "🏈": "football american",
  "⚾": "baseball",
  "🎾": "tennis",
  "🏓": "ping pong",
  "🎮": "video game",
  "🎯": "dart target",
  "🎳": "bowling",
  "🏆": "trophy winner",
  "🥇": "gold medal",
  "🥈": "silver medal",
  "🥉": "bronze medal",
  "🎨": "art palette",
  "🎬": "cinema movie",
  "🎤": "microphone sing",
  "🎧": "headphones music",
  "🎸": "guitar",
  "🎹": "piano keyboard",
  "🎺": "trumpet",
  "🎻": "violin",
  "🚗": "car",
  "🚕": "taxi",
  "🚌": "bus",
  "🚓": "police car",
  "🚑": "ambulance",
  "🚒": "fire truck",
  "🚲": "bicycle bike",
  "🏍️": "motorcycle motorbike",
  "✈️": "airplane plane",
  "🚀": "rocket",
  "🛸": "ufo flying saucer",
  "🚁": "helicopter",
  "⛵": "sailboat boat",
  "🚢": "ship",
  "🗺️": "map",
  "🌍": "earth globe world",
  "🌎": "earth globe",
  "🌏": "earth globe",
  "🏠": "house home",
  "🏡": "house home",
  "🏢": "building office",
  "🏥": "hospital",
  "🏦": "bank",
  "🏫": "school",
  "🏰": "castle",
  "⛪": "church",
  "🕌": "mosque",
  // Objects & Symbols
  "⌚": "watch",
  "📱": "phone smartphone mobile",
  "💻": "computer laptop",
  "⌨️": "keyboard",
  "🖥️": "computer desktop",
  "📷": "camera",
  "📸": "camera photo",
  "📹": "video camera",
  "🎥": "camera movie",
  "📺": "tv television",
  "📻": "radio",
  "⏰": "alarm clock",
  "⏳": "hourglass time",
  "📡": "satellite antenna",
  "🔋": "battery",
  "💡": "light bulb idea",
  "💰": "money cash",
  "💳": "credit card",
  "💎": "diamond gem",
  "🔧": "wrench tool",
  "🔨": "hammer",
  "🔑": "key",
  "🔒": "lock locked",
  "🔓": "unlock unlocked",
  "💄": "lipstick makeup",
  "💍": "ring",
  "👑": "crown king",
  "🎓": "graduation cap",
  "💼": "briefcase work",
  "🎒": "backpack school",
  "❤️": "heart love red",
  "🧡": "heart orange",
  "💛": "heart yellow",
  "💚": "heart green",
  "💙": "heart blue",
  "💜": "heart purple",
  "🖤": "heart black",
  "🤍": "heart white",
  "💔": "broken heart",
  "💕": "two hearts love",
  "💓": "beating heart",
  "💗": "growing heart",
  "💖": "sparkling heart",
  "💘": "heart arrow love",
  "💯": "hundred perfect score",
  "💢": "anger symbol",
  "🔥": "fire hot flame",
  "✨": "sparkles star",
  "⭐": "star",
  "🎉": "party celebration confetti",
  "🎊": "confetti celebration",
  "❗": "exclamation",
  "❓": "question",
  "✅": "check mark done",
  "❌": "cross no wrong",
  "⚠️": "warning danger",
  "♻️": "recycle",
  "➕": "plus",
  "➖": "minus",
  "➗": "divide",
  "✖️": "multiply"
};

/**
 * The shortcodes people already know from other chat apps. Without them the
 * generated list below answers on a first-come basis, which hands `:fire:` to
 * the fire engine and `:heart:` to the smiley with heart eyes.
 */
export const EMOJI_ALIASES: Record<string, string> = {
  "100": "💯",
  alien: "👽",
  angry: "😠",
  beer: "🍺",
  bug: "🐛",
  bulb: "💡",
  cake: "🎂",
  check: "✅",
  clap: "👏",
  coffee: "☕",
  crown: "👑",
  cry: "😢",
  eyes: "👀",
  fire: "🔥",
  ghost: "👻",
  heart: "❤️",
  joy: "😂",
  key: "🔑",
  kiss: "😘",
  lock: "🔒",
  love: "😍",
  moneybag: "💰",
  muscle: "💪",
  ok: "👌",
  party: "🎉",
  poop: "💩",
  pray: "🙏",
  robot: "🤖",
  rocket: "🚀",
  skull: "💀",
  smile: "😄",
  sob: "😭",
  sparkles: "✨",
  star: "⭐",
  sunglasses: "😎",
  tada: "🎉",
  thinking: "🤔",
  thumbsdown: "👎",
  thumbsup: "👍",
  warning: "⚠️",
  wave: "👋",
  wink: "😉",
  x: "❌"
};

/**
 * `:name:` shortcodes, built from the same keyword list the picker searches,
 * with the aliases above taking precedence. The first emoji to claim a
 * remaining word keeps it, so a given shortcode always produces the same
 * character.
 */
export const EMOJI_SHORTCODES: Record<string, string> = (() => {
  const map: Record<string, string> = { ...EMOJI_ALIASES };
  for (const [emoji, names] of Object.entries(EMOJI_NAMES)) {
    for (const word of String(names).split(/\s+/)) {
      const code = word.toLowerCase();
      if (code.length >= 2 && !(code in map)) map[code] = emoji;
    }
  }
  return map;
})();

export const flagNames: Record<string, string> = (() => {
  const names: Record<string, string> = { ...FLAG_EXTRA_NAMES };
  let regionName: Intl.DisplayNames | null = null;
  try {
    regionName = new Intl.DisplayNames(["en"], { type: "region" });
  } catch {
    regionName = null;
  }
  for (const code of FLAG_REGIONS) {
    let label = "";
    try {
      label = regionName?.of(code) ?? "";
    } catch {
      label = "";
    }
    names[regionFlag(code)] = `flag ${code} ${label}`.toLowerCase();
  }
  return names;
})();

export function emojiMatchesQuery(emoji: string, q: string): boolean {
  if (!q) return true;
  if (emoji.toLowerCase().includes(q)) return true;
  const names = EMOJI_NAMES[emoji] ?? flagNames[emoji];
  return Boolean(names && names.includes(q));
}
